language: ruby
rvm:
  - 2.6.0

before_install:
  - gem update --system
  - gem install bundler
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.22.0-linux64.tar.gz -C bin
  - export PATH=$(pwd)/bin:$PATH

addons:
  firefox: latest
  postgresql: "9.6"

services:
  - postgresql
  - mysql
  - redis

before_script:
  - psql -c 'create database "octobox_test";' -U postgres || true
  - mysql -u root -e 'create database octobox_test;' || true

script:
  - RAILS_ENV=test bundle exec rake --trace rubocop db:migrate test:skip_visuals

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

env:
  global:
    - MOZ_HEADLESS=1
  matrix:
    - DATABASE=mysql2
    - DATABASE=postgresql

notifications:
  email: false
