#!/bin/bash

file_he='log/1-file_list-helpers.txt'
file_mo='log/1-file_list-models.txt'
file_co='log/1-file_list-controllers.txt'
file_li='log/1-file_list-libraries.txt'
file_jo='log/1-file_list-jobs.txt'
file_ch='log/1-file_list-channels.txt'
file_vi='log/1-file_list-views.txt'

sh pg-start.sh

echo '------------------------------------'
echo 'Listing the helper files in the file'
echo $file_he
echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_he
echo '-------------------' >> $file_he
echo 'HELPERS' >> $file_he
tree test/helpers >> $file_he
echo '' >> $file_he
tree app/helpers >> $file_he
echo '' >> $file_he

echo '-----------------------------------'
echo 'Listing the model files in the file'
echo $file_mo
echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_mo
echo '------' >> $file_mo
echo 'MODELS' >> $file_mo
tree test/models >> $file_mo
echo '' >> $file_mo
tree test/fixtures >> $file_mo
echo '' >> $file_mo
tree app/models >> $file_mo

echo '----------------------------------------'
echo 'Listing the controller files in the file'
echo $file_co
echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_co
echo '-----------' >> $file_co
echo 'CONTROLLERS' >> $file_co
tree test/controllers >> $file_co
echo '' >> $file_co
tree app/controllers >> $file_co

echo '---------------------------------'
echo 'Listing the library files in file'
echo $file_li
echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_li
echo '-----------' >> $file_li
echo 'LIBRARIES' >> $file_li
tree test/lib >> $file_li
echo '' >> $file_li
tree lib >> $file_li

echo '---------------------------------'
echo 'Listing the channel files in file'
echo $file_ch
echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_ch
echo '--------' >> $file_ch
echo 'CHANNELS' >> $file_ch
tree test/channels >> $file_ch
echo '' >> $file_ch
tree app/channels >> $file_ch

echo '-----------------------------'
echo 'Listing the job files in file'
echo $file_jo
echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_jo
echo '-------' >> $file_jo
echo 'WORKERS' >> $file_jo
tree test/workers >> $file_jo
echo '' >> $file_jo
tree app/workers >> $file_jo


echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_vi
echo '---------------------------' >> $file_vi
echo 'VIEWS AND INTEGRATION TESTS' >> $file_vi
echo '' >> $file_vi
echo '----------------' >> $file_vi
echo 'config/routes.rb' >> $file_vi
cat config/routes.rb >> $file_vi
echo '----------------' >> $file_vi
tree test/integration >> $file_vi
echo '' >> $file_vi
tree app/views >> $file_vi

echo 'FINISHED compiling the list of files that make up the MVC structure'
echo '-------------------------------------------------------------------'

echo '******************************'
echo 'outline-short.sh OUTPUT FILES:'
echo $file_he
echo $file_mo
echo $file_co
echo $file_li
echo $file_ch
echo $file_jo
echo $file_vi
echo
